image: python:3.6

variables:
  REGISTRY: test-registry.pooq.co.kr

stages:
  - test
  - build

unittest:
  stage: test
  script:
    - pip install -r app/requirements.txt
    - python app/test.py

build_docker_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME .
    - docker push $CI_REGISTRY/flask-test-for-gitlab
