image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2
  CI_ENVIRONMENT_NAME: nametest01
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  LATEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build --pull -t $COMMIT_IMAGE_TAG .
    - docker push $COMMIT_IMAGE_TAG
    - echo $CI_ENVIRONMENT_SLUG
  environment:
    name: $CI_PROJECT_NAME

unittest1:
  stage: test
  script:
    - docker pull $COMMIT_IMAGE_TAG
    - docker run --rm -e "MODE=TEST1" $COMMIT_IMAGE_TAG

unittest2:
  stage: test
  script:
    - docker pull $COMMIT_IMAGE_TAG
    - docker run --rm -e "MODE=TEST2" $COMMIT_IMAGE_TAG

release-image:
  stage: release
  script:
    - docker pull $COMMIT_IMAGE_TAG
    - docker tag $COMMIT_IMAGE_TAG $LATEST_IMAGE_TAG
    - docker push $LATEST_IMAGE_TAG
  only:
    - master
