image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2
  TEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:test
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:CI_COMMIT_SHA

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE_TAG .
    - docker push $TEST_IMAGE_TAG

unittest1:
  stage: test
  script:
    - docker pull $TEST_IMAGE_TAG
    - docker run --rm --entrypoint="python test1.py" $TEST_IMAGE_TAG

unittest2:
  stage: test
  script:
    - docker pull $TEST_IMAGE_TAG
    - docker run --rm --entrypoint="python test2.py" $TEST_IMAGE_TAG

release-image:
  stage: release
  script:
    - docker pull $TEST_IMAGE_TAG
    - docker tag $TEST_IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
  only:
    - master
